/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.resilience4j.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
